### ISSUE TITLE
Add no-cursor via JS

### ISSUE THREAD

**Issue by paulzz3000** [dshongphuc/magic-mouse-js#18]
Me again (love the effect—you should sell it)...
Trying to add no-cursor like this:
jQuery(document).ready(function($) {
$('.whatever').addClass( 'no-cursor' );
});
No joy. The class is added but ignored.

**Comment by dshongphuc** [comment]
@paulzz3000 well, the problem is Magicmouse auto-detect `.no-cursor` divs right after the page loaded. This means that when you add `.no-cursor` class AFTER the moment Magicmouse has been initialized, your new classes will be ignored.
So my suggestion is that you should only init Magicmouse AFTER you add all those classes dynamically.

> Me again (love the effect—you should sell it)...
Btw, thank you so much for your sweet words :D And no I won't sell anything. In fact, I'm planning to add more effects to this libs but am too busy currently so I will do that when I have time.

**Comment by paulzz3000** [comment]
Thank you! I have no idea how to do that but I’ll work it out!

Best

Paul

**Comment by paulzz3000** [comment]
Did it! Thank you again.
