### ISSUE TITLE
Over embed youtube video ?

### ISSUE THREAD

**Issue by urbanmythology** [dshongphuc/magic-mouse-js#47]
Works fine in a basic way using Wordpress/Elementor installation

But impossible to go over an embed youtude video, cursor stops at the edge of the 

Is it possible to fix it ? 
Thank you!! 
 
<img width="1279" alt="Capture d’écran 2023-05-23 à 13 39 31" src="https://github.com/dshongphuc/magic-mouse-js/assets/134390266/bebc0189-50e6-4725-9149-1eb074c96d96">

**Comment by dshongphuc** [comment]
Hi @urbanmythology , thanks for your report.
I've tried to fix this but unfortunately, this is impossible. Because you're embedding a video from another domain (Youtube in this case), and browsers don't allow us to track anything in an iframe of another site, it violates the [same origin policy](http://en.wikipedia.org/wiki/Same_origin_policy).
I suggest that you should add class `no-cursor` to that iframe, so when your cursor moves to the iframe, the Magicmouse will disappear and become a normal cursor
